@startuml
'!theme plain
skinparam linetype ortho

node "Dispositivo Android" as mobile {
  component "App Flutter" as flutter
  
}

node "Servidor Backend" as backend {
  component "Ruby Sinatra\n(REST API)" as sinatra
  database "SQLite3\n(sqflite)" as db
  sinatra -- db
}

cloud "Servicios Externos" as ext {
  component "OpenStreetMap" as osm
}

flutter --> sinatra : HTTP/REST (JSON)
flutter ---> osm : HTTPS (Map Tiles)

@enduml